export const FACE_SMASHING = {
    viewScale: 2.25,
    postProcess: {
        shadowTint: [1.0, 0.9, 0.82] as const,
        highlightTint: [1.05, 0.99, 0.9] as const,
        gradeStrength: 0.2,
        vignette: 0.5,
        vignetteInner: 0.4,
        grain: 0.025,
        bloom: 0.28,
        bloomThreshold: 0.72,
        saturation: 1.08,
    },
    tile: {
        size: 16,
        scale: 2,
        columns: 20,
        rows: 15,
        wallThickness: 2,
        floorThickness: 1,
        ceilingRows: 3,
    },
    physics: {
        gravity: 900,
        friction: 0.82,
    },
    dodger: {
        box: { width: 24, height: 26 },
        idleSpeed: 6,
        runSpeed: 78,
        walkStride: 44,
        runStride: 72,
        maxSpeedStart: 131,
        maxSpeedEnd: 89,
        jumpStart: 588,
        jumpEnd: 320,
        accelerationX: 2898,
        dragX: 6,
        maxFallSpeed: 900,
    },
    dash: {
        speedStart: 1000,
        speedEnd: 400,
        seconds: 0.16,
        cooldownSeconds: 2.5,
        ghostCount: 5,
        trailAfter: 0.1,
        trailAlpha: 0.42,
    },
    damage: {
        levels: 8,
        perLevel: 100,
    },
    item: {
        gravity: 417,
        maxFallSpeed: 250,
        spawnHeight: 24,
        groundFriction: 2.4,
        restitution: 0.35,
        spinTransfer: 0.55,
        settleSeconds: 0.6,
        fadeSeconds: 0.45,
        appearSeconds: 0.22,
        appearScale: 0.45,
        despawnBelow: 32,
        referenceSpeed: 143,
        spinDamageBonus: 0.4,
        speedFactorMin: 0.6,
        speedFactorMax: 1.8,
    },
    itemDash: {
        speed: 620,
        seconds: 0.28,
        spinBoost: 1.6,
        ghostCount: 6,
        trailAfter: 0.12,
        trailAlpha: 0.5,
        stretch: 0.34,
    },
    drop: {
        baseSpeed: 71,
        maxSpeed: 238,
        speedStep: 21,
        rampSeconds: 3,
        steerSpeed: 270,
        thrust: 238,
    },
    spawnMarker: {
        size: 26,
        maxAngle: 1.35,
        color: '#e0a44a',
        highlight: '#f7cd72',
        shade: '#a06a26',
        outline: '#0a0908',
        smoothingSeconds: 0.05,
    },
    round: {
        seconds: 60,
        restartDelay: 1.4,
    },
    impact: {
        nearMissDistance: 12,
        dodgeDistance: 24,
    },
    reaction: {
        knockbackBase: 130,
        knockbackPerDamage: 4.2,
        knockbackMax: 620,
        pop: 190,
        stunSeconds: 0.28,
        flashSeconds: 0.2,
        invulnerableSeconds: 0.5,
        flashColor: '#ffffff',
    },
    player: {
        /** Sprinting speed, as a fraction of the damaged-tier max speed. */
        runSpeedFactor: 1,
        /** Tapping a direction moves this fraction of the sprint speed. */
        walkSpeedFactor: 1,
    },
    effects: {
        impact: { frames: 6, frameDuration: 0.05 },
        slash: { frames: 6, frameDuration: 0.055 },
        dust: { frames: 6, frameDuration: 0.06 },
        explosion: { frames: 7, frameDuration: 0.055 },
    },
    ai: {
        modelUrl: 'models/dodger-policy.json',
        observationSize: 77,
        actionCount: 8,
        observeRadius: 576,
        sensorReach: 192,
    },
    scorePopup: {
        duration: 0.9,
        rise: 30,
        capacity: 16,
        fontSize: 26,
        color: '#f4ecd8',
        outline: '#0a0908',
    },
    match: {
        defaultDurationSeconds: 60,
        minDurationSeconds: 5,
        maxDurationSeconds: 300,
        durationStepSeconds: 15,
    },
};

export type FaceSmashingConfig = typeof FACE_SMASHING;
