import type { GradientRamp } from '../../engine/render';

export const FACE_SMASHING = {
    viewScale: 2.25,
    backdrop: {
        top: '#0e211d',
        bottom: '#050b0a',
        hearthGlow: 'rgba(40, 96, 74, 0.30)',
        shaftGlow: 'rgba(150, 210, 170, 0.26)',
        torchGlow: 'rgba(255, 196, 110, 0.44)',
        torchRadius: 6,
        torchPoolAlpha: 0.26,
        propTint: 'rgba(52, 78, 62, 0.62)',
        wallShade: 0.48,
        wallVariation: 0.26,
        floorVariation: 0.18,
        vignetteStrength: 0.78,
        vignetteRadius: 0.15,
        ceilingShadeHeight: 0.30,
        hazeAlpha: 0.22,
        canopyDepths: 3,
        canopyMassCount: [18, 12, 8],
        canopySeed: 0x51ed270b,
    },
    postProcess: {
        shadowTint: [0.78, 1.02, 0.94] as const,
        highlightTint: [1.06, 1.02, 0.92] as const,
        gradeStrength: 0.22,
        vignette: 0.42,
        vignetteInner: 0.42,
        grain: 0.02,
        bloom: 0.32,
        bloomThreshold: 0.72,
        saturation: 1.18,
    },
    palette: {
        wall: [
            { luminance: 0, color: [10, 24, 24] },
            { luminance: 0.28, color: [24, 56, 48] },
            { luminance: 0.52, color: [46, 96, 72] },
            { luminance: 0.76, color: [94, 142, 96] },
            { luminance: 1, color: [182, 206, 152] },
        ] as GradientRamp,
        canopy: [
            { luminance: 0, color: [7, 18, 17] },
            { luminance: 0.32, color: [14, 34, 30] },
            { luminance: 0.6, color: [22, 48, 40] },
            { luminance: 1, color: [36, 68, 54] },
        ] as GradientRamp,
    },
    tile: {
        size: 16,
        scale: 2,
        columns: 20,
        rows: 12,
        wallThickness: 2,
        floorThickness: 1,
    },
    physics: {
        gravity: 900,
        friction: 0.82,
    },
    dodger: {
        box: { width: 24, height: 26 },
        maxSpeedStart: 560,
        maxSpeedEnd: 150,
        jumpStart: 588,
        jumpEnd: 320,
        accelerationX: 7376,
        dragX: 6,
        maxFallSpeed: 900,
    },
    dash: {
        speedStart: 1000,
        speedEnd: 400,
        seconds: 0.16,
        cooldownSeconds: 1,
        ghostCount: 5,
        trailAfter: 0.1,
        trailAlpha: 0.42,
    },
    damage: {
        levels: 8,
        perLevel: 500,
    },
    item: {
        gravity: 900,
        maxFallSpeed: 520,
        spawnMargin: 40,
        spawnHeight: 24,
        lateralSpeed: 20,
        groundFriction: 2.4,
        restitution: 0.35,
        spinTransfer: 0.55,
        settleSeconds: 1.2,
        despawnBelow: 32,
        referenceSpeed: 240,
        spinDamageBonus: 0.4,
        speedFactorMin: 0.6,
        speedFactorMax: 1.8,
    },
    drop: {
        baseSpeed: 140,
        maxSpeed: 500,
        speedStep: 40,
        baseInterval: 1.05,
        minInterval: 0.4,
        rampSeconds: 3,
        horizontalSpeed: 200,
        fastFallSpeed: 700,
        aimSpeed: 260,
        aimJitter: 20,
        maxLead: 0.9,
        scatter: 0.05,
    },
    round: {
        seconds: 60,
        restartDelay: 1.4,
        damageWeight: 1,
        scoreWeight: 1,
    },
    impact: {
        nearMissDistance: 12,
        dodgeDistance: 24,
    },
    reaction: {
        knockbackBase: 130,
        knockbackPerDamage: 4.2,
        knockbackMax: 620,
        pop: 190,
        stunSeconds: 0.28,
        flashSeconds: 0.2,
        invulnerableSeconds: 0.5,
        flashColor: '#ffffff',
    },
    effects: {
        impact: { frames: 6, frameDuration: 0.05 },
        slash: { frames: 6, frameDuration: 0.055 },
        dust: { frames: 6, frameDuration: 0.06 },
    },
    ai: {
        modelUrl: 'models/dodger-policy.json',
        observationSize: 77,
        actionCount: 8,
        observeRadius: 576,
        sensorReach: 192,
    },
    score: {
        survivedPerSecond: 10,
        dodge: 5,
        nearMiss: 1,
    },
    match: {
        defaultDurationSeconds: 60,
        minDurationSeconds: 5,
        maxDurationSeconds: 300,
        durationStepSeconds: 15,
    },
};

export type FaceSmashingConfig = typeof FACE_SMASHING;
