/**
 * Runtime catalog of the audio assets.
 *
 * The file names are never hardcoded: `public/assets/audio/manifest.json` is
 * generated by `tools/build_audio_manifest.py` and lists every sound, grouped
 * by the folder that decides its mixer channel:
 *
 * - `soundtrack/`     -> music volume
 * - `voices/<set>/`   -> voice volume (the set is picked in the configuration)
 * - `sound_effects/`  -> sound-effect volume (one group per folder/event)
 *
 * Paths inside the manifest are relative to the audio folder; they are
 * resolved into `assets/audio/...` URLs while loading.
 */

export interface VoiceSetManifestEntry {
    /** Folder name under `voices/`; also the i18n key of its label. */
    key: string;
    files: readonly string[];
}

/** One sound event (`button_hover`, `impact`, ...) with all its variants. */
export interface SoundEffectGroup {
    /** Folder name; the name the game asks for when playing it. */
    key: string;
    files: readonly string[];
}

export interface AudioManifest {
    soundtrack: { tracks: readonly string[] };
    voices: { sets: readonly VoiceSetManifestEntry[] };
    soundEffects: { groups: readonly SoundEffectGroup[] };
}

/** Folder (inside `public/assets/`) that holds every audio file. */
export const AUDIO_BASE_PATH = 'assets/audio';

export const AUDIO_MANIFEST_URL = `${AUDIO_BASE_PATH}/manifest.json`;

export const EMPTY_AUDIO_MANIFEST: AudioManifest = {
    soundtrack: { tracks: [] },
    voices: { sets: [] },
    soundEffects: { groups: [] },
};

/** Turns a manifest path (e.g. `voices/set_a/normal-1.mp3`) into a URL. */
export function audioUrl(path: string): string {
    return `${AUDIO_BASE_PATH}/${path}`;
}

/** Every file listed in the manifest; used to preload them all at boot. */
export function manifestUrls(manifest: AudioManifest): string[] {
    return [
        ...manifest.soundtrack.tracks,
        ...manifest.voices.sets.flatMap((set) => set.files),
        ...manifest.soundEffects.groups.flatMap((group) => group.files),
    ];
}

/**
 * Validates and normalises the raw JSON. Unknown shapes are dropped instead of
 * throwing, so a hand-edited manifest can never break the game boot.
 */
export function parseAudioManifest(raw: unknown): AudioManifest {
    const root = asRecord(raw);
    const soundtrack = asRecord(root?.['soundtrack']);
    const voices = asRecord(root?.['voices']);
    const soundEffects = asRecord(root?.['soundEffects']);

    return {
        soundtrack: { tracks: stringList(soundtrack?.['tracks']).map(audioUrl) },
        voices: { sets: groupedEntries(voices?.['sets']) },
        soundEffects: { groups: groupedEntries(soundEffects?.['groups']) },
    };
}

/** Default loader: fetches the generated manifest; empty on any failure. */
export async function loadAudioManifest(): Promise<AudioManifest> {
    if (typeof fetch !== 'function') {
        return EMPTY_AUDIO_MANIFEST;
    }

    try {
        const response = await fetch(AUDIO_MANIFEST_URL);
        if (!response.ok) {
            return EMPTY_AUDIO_MANIFEST;
        }

        return parseAudioManifest(await response.json());
    } catch {
        return EMPTY_AUDIO_MANIFEST;
    }
}

function groupedEntries(raw: unknown): { key: string; files: string[] }[] {
    if (!Array.isArray(raw)) {
        return [];
    }

    return raw.flatMap((entry) => {
        const record = asRecord(entry);
        const key = record?.['key'];

        if (typeof key !== 'string' || key.length === 0) {
            return [];
        }

        return [{ key, files: stringList(record?.['files']).map(audioUrl) }];
    });
}

function asRecord(value: unknown): Record<string, unknown> | null {
    return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : null;
}

function stringList(value: unknown): string[] {
    if (!Array.isArray(value)) {
        return [];
    }

    return value.filter((entry): entry is string => typeof entry === 'string' && entry.length > 0);
}
